export const cartActionTypes = {
    CART_TOGGLE_VISIBLE: 'CART_TOGGLE_VISIBLE',
    CART_ITEM_ADD: 'CART_ITEM_ADD',     //same as increace
    CART_ITEM_REMOVE: 'CART_ITEM_REMOVE',
    CART_ITEM_DECREACE: 'CART_ITEM_DECREACE',
}