export const userActionTypes = {
    USER_CRED_SIGNIN_START: 'USER_CRED_SIGNIN_START',
    USER_CRED_SIGNIN_SUCCESS: 'USER_CRED_SIGNIN_SUCCESS',
    USER_CRED_SIGNIN_FAILURE: 'USER_CRED_SIGNIN_FAILURE',

    USER_CRED_SIGNUP_START: 'USER_CRED_SIGNUP_START',
    USER_CRED_SIGNUP_SUCCESS: 'USER_CRED_SIGNUP_SUCCESS',
    USER_CRED_SIGNUP_FAILURE: 'USER_CRED_SIGNUP_FAILURE',

    USER_GOOGLE_AUTH_START: 'USER_GOOGLE_AUTH_START',
    USER_GOOGLE_AUTH_SUCCESS: 'USER_GOOGLE_AUTH_SUCCESS',
    USER_GOOGLE_AUTH_FAILURE: 'USER_GOOGLE_AUTH_FAILURE',

    USER_AUTO_SIGNIN_SUCCESS: 'USER_AUTO_SIGNIN_SUCCESS',
    USER_AUTO_SIGNIN_FAILURE: 'USER_AUTO_SIGNIN_FAILURE',

    USER_SIGNOUT_START: 'USER_SIGNOUT_START',
    USER_SIGNOUT_SUCCESS: 'USER_SIGNOUT_SUCCESS',
    USER_SIGNOUT_FAILURE: 'USER_SIGNOUT_FAILURE',

    USER_STATE_CHANGED: 'USER_STATE_CHANGED',
}