export const userActionTypes = {
    USER_AUTH_CREDENTIALS_START: 'USER_AUTH_CREDENTIALS_START',
    USER_AUTH_CREDENTIALS_SUCCESS: 'USER_AUTH_CREDENTIALS_SUCCESS',
    USER_AUTH_CREDENTIALS_FAILURE: 'USER_AUTH_CREDENTIALS_FAILURE',

    USER_AUTH_GOOGLE_START: 'USER_AUTH_GOOGLE_START',
    USER_AUTH_GOOGLE_SUCCESS: 'USER_AUTH_GOOGLE_SUCCESS',
    USER_AUTH_GOOGLE_FAILURE: 'USER_AUTH_GOOGLE_FAILURE',

    USER_AUTH_STATE_CHANGED: 'USER_AUTH_STATE_CHANGED',
}