export const categoriesActionTypes = {
    CATEGORIEST_FETCH_START: 'CATEGORIEST_FETCH_START',
    CATEGORIEST_FETCH_SUCCESS: 'CATEGORIEST_FETCH_SUCCESS',
    CATEGORIEST_FETCH_FAILURE: 'CATEGORIEST_FETCH_FAILURE',
}